# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
